// Code generated by protoc-gen-go. DO NOT EDIT.
// source: users.proto

package api_pb

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import _ "google.golang.org/genproto/googleapis/api/annotations"
import field_mask "google.golang.org/genproto/protobuf/field_mask"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Email                string   `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	FullName             string   `protobuf:"bytes,4,opt,name=full_name,json=fullName,proto3" json:"full_name,omitempty"`
	AvatarUrl            string   `protobuf:"bytes,5,opt,name=avatar_url,json=avatarUrl,proto3" json:"avatar_url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_deb224c9cb6eedaa, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *User) GetAvatarUrl() string {
	if m != nil {
		return m.AvatarUrl
	}
	return ""
}

type ListUsersRequest struct {
	PageToken            uint32   `protobuf:"varint,1,opt,name=page_token,json=pageToken,proto3" json:"page_token,omitempty"`
	PageSize             int32    `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersRequest) Reset()         { *m = ListUsersRequest{} }
func (m *ListUsersRequest) String() string { return proto.CompactTextString(m) }
func (*ListUsersRequest) ProtoMessage()    {}
func (*ListUsersRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_deb224c9cb6eedaa, []int{1}
}
func (m *ListUsersRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersRequest.Unmarshal(m, b)
}
func (m *ListUsersRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersRequest.Marshal(b, m, deterministic)
}
func (dst *ListUsersRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersRequest.Merge(dst, src)
}
func (m *ListUsersRequest) XXX_Size() int {
	return xxx_messageInfo_ListUsersRequest.Size(m)
}
func (m *ListUsersRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersRequest proto.InternalMessageInfo

func (m *ListUsersRequest) GetPageToken() uint32 {
	if m != nil {
		return m.PageToken
	}
	return 0
}

func (m *ListUsersRequest) GetPageSize() int32 {
	if m != nil {
		return m.PageSize
	}
	return 0
}

type ListUsersResponse struct {
	Users                []*User  `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	NextPageToken        uint32   `protobuf:"varint,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ListUsersResponse) Reset()         { *m = ListUsersResponse{} }
func (m *ListUsersResponse) String() string { return proto.CompactTextString(m) }
func (*ListUsersResponse) ProtoMessage()    {}
func (*ListUsersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_deb224c9cb6eedaa, []int{2}
}
func (m *ListUsersResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListUsersResponse.Unmarshal(m, b)
}
func (m *ListUsersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListUsersResponse.Marshal(b, m, deterministic)
}
func (dst *ListUsersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListUsersResponse.Merge(dst, src)
}
func (m *ListUsersResponse) XXX_Size() int {
	return xxx_messageInfo_ListUsersResponse.Size(m)
}
func (m *ListUsersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ListUsersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ListUsersResponse proto.InternalMessageInfo

func (m *ListUsersResponse) GetUsers() []*User {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *ListUsersResponse) GetNextPageToken() uint32 {
	if m != nil {
		return m.NextPageToken
	}
	return 0
}

type GetUserRequest struct {
	UserId               uint32   `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_deb224c9cb6eedaa, []int{3}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUserId() uint32 {
	if m != nil {
		return m.UserId
	}
	return 0
}

type CreateUserRequest struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	RegisterationToken   string   `protobuf:"bytes,2,opt,name=registeration_token,json=registerationToken,proto3" json:"registeration_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_deb224c9cb6eedaa, []int{4}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *CreateUserRequest) GetRegisterationToken() string {
	if m != nil {
		return m.RegisterationToken
	}
	return ""
}

type UpdateUserRequest struct {
	User                 *User                 `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	UpdateMask           *field_mask.FieldMask `protobuf:"bytes,2,opt,name=update_mask,json=updateMask,proto3" json:"update_mask,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *UpdateUserRequest) Reset()         { *m = UpdateUserRequest{} }
func (m *UpdateUserRequest) String() string { return proto.CompactTextString(m) }
func (*UpdateUserRequest) ProtoMessage()    {}
func (*UpdateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_deb224c9cb6eedaa, []int{5}
}
func (m *UpdateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdateUserRequest.Unmarshal(m, b)
}
func (m *UpdateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdateUserRequest.Marshal(b, m, deterministic)
}
func (dst *UpdateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdateUserRequest.Merge(dst, src)
}
func (m *UpdateUserRequest) XXX_Size() int {
	return xxx_messageInfo_UpdateUserRequest.Size(m)
}
func (m *UpdateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdateUserRequest proto.InternalMessageInfo

func (m *UpdateUserRequest) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UpdateUserRequest) GetUpdateMask() *field_mask.FieldMask {
	if m != nil {
		return m.UpdateMask
	}
	return nil
}

type UpdatePasswordRequest struct {
	UserId               string   `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	NewPassword          string   `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	NewPasswordRepeat    string   `protobuf:"bytes,4,opt,name=new_password_repeat,json=newPasswordRepeat,proto3" json:"new_password_repeat,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpdatePasswordRequest) Reset()         { *m = UpdatePasswordRequest{} }
func (m *UpdatePasswordRequest) String() string { return proto.CompactTextString(m) }
func (*UpdatePasswordRequest) ProtoMessage()    {}
func (*UpdatePasswordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_users_deb224c9cb6eedaa, []int{6}
}
func (m *UpdatePasswordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpdatePasswordRequest.Unmarshal(m, b)
}
func (m *UpdatePasswordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpdatePasswordRequest.Marshal(b, m, deterministic)
}
func (dst *UpdatePasswordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpdatePasswordRequest.Merge(dst, src)
}
func (m *UpdatePasswordRequest) XXX_Size() int {
	return xxx_messageInfo_UpdatePasswordRequest.Size(m)
}
func (m *UpdatePasswordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UpdatePasswordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UpdatePasswordRequest proto.InternalMessageInfo

func (m *UpdatePasswordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *UpdatePasswordRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPassword() string {
	if m != nil {
		return m.NewPassword
	}
	return ""
}

func (m *UpdatePasswordRequest) GetNewPasswordRepeat() string {
	if m != nil {
		return m.NewPasswordRepeat
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "com.github.ProgrammingLab.prolab_accounts.api.User")
	proto.RegisterType((*ListUsersRequest)(nil), "com.github.ProgrammingLab.prolab_accounts.api.ListUsersRequest")
	proto.RegisterType((*ListUsersResponse)(nil), "com.github.ProgrammingLab.prolab_accounts.api.ListUsersResponse")
	proto.RegisterType((*GetUserRequest)(nil), "com.github.ProgrammingLab.prolab_accounts.api.GetUserRequest")
	proto.RegisterType((*CreateUserRequest)(nil), "com.github.ProgrammingLab.prolab_accounts.api.CreateUserRequest")
	proto.RegisterType((*UpdateUserRequest)(nil), "com.github.ProgrammingLab.prolab_accounts.api.UpdateUserRequest")
	proto.RegisterType((*UpdatePasswordRequest)(nil), "com.github.ProgrammingLab.prolab_accounts.api.UpdatePasswordRequest")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserServiceClient interface {
	ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
	CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error)
	UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error)
}

type userServiceClient struct {
	cc *grpc.ClientConn
}

func NewUserServiceClient(cc *grpc.ClientConn) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) ListUsers(ctx context.Context, in *ListUsersRequest, opts ...grpc.CallOption) (*ListUsersResponse, error) {
	out := new(ListUsersResponse)
	err := c.cc.Invoke(ctx, "/com.github.ProgrammingLab.prolab_accounts.api.UserService/ListUsers", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/com.github.ProgrammingLab.prolab_accounts.api.UserService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) CreateUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/com.github.ProgrammingLab.prolab_accounts.api.UserService/CreateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdateUser(ctx context.Context, in *UpdateUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/com.github.ProgrammingLab.prolab_accounts.api.UserService/UpdateUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UpdatePassword(ctx context.Context, in *UpdatePasswordRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/com.github.ProgrammingLab.prolab_accounts.api.UserService/UpdatePassword", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
type UserServiceServer interface {
	ListUsers(context.Context, *ListUsersRequest) (*ListUsersResponse, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
	CreateUser(context.Context, *CreateUserRequest) (*User, error)
	UpdateUser(context.Context, *UpdateUserRequest) (*User, error)
	UpdatePassword(context.Context, *UpdatePasswordRequest) (*empty.Empty, error)
}

func RegisterUserServiceServer(s *grpc.Server, srv UserServiceServer) {
	s.RegisterService(&_UserService_serviceDesc, srv)
}

func _UserService_ListUsers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ListUsers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.ProgrammingLab.prolab_accounts.api.UserService/ListUsers",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ListUsers(ctx, req.(*ListUsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.ProgrammingLab.prolab_accounts.api.UserService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_CreateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).CreateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.ProgrammingLab.prolab_accounts.api.UserService/CreateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).CreateUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdateUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdateUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.ProgrammingLab.prolab_accounts.api.UserService/UpdateUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdateUser(ctx, req.(*UpdateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UpdatePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePasswordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UpdatePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/com.github.ProgrammingLab.prolab_accounts.api.UserService/UpdatePassword",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UpdatePassword(ctx, req.(*UpdatePasswordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _UserService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "com.github.ProgrammingLab.prolab_accounts.api.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListUsers",
			Handler:    _UserService_ListUsers_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _UserService_GetUser_Handler,
		},
		{
			MethodName: "CreateUser",
			Handler:    _UserService_CreateUser_Handler,
		},
		{
			MethodName: "UpdateUser",
			Handler:    _UserService_UpdateUser_Handler,
		},
		{
			MethodName: "UpdatePassword",
			Handler:    _UserService_UpdatePassword_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "users.proto",
}

func init() { proto.RegisterFile("users.proto", fileDescriptor_users_deb224c9cb6eedaa) }

var fileDescriptor_users_deb224c9cb6eedaa = []byte{
	// 672 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x95, 0x4f, 0x4f, 0x13, 0x41,
	0x18, 0xc6, 0x33, 0xd0, 0x96, 0xee, 0x5b, 0xa9, 0x74, 0x00, 0xad, 0x8b, 0x24, 0x65, 0x4d, 0x0c,
	0x1e, 0xdc, 0x4d, 0xca, 0x4d, 0x63, 0x34, 0xfe, 0x23, 0x24, 0x48, 0xc8, 0x22, 0x17, 0x2f, 0x9b,
	0x69, 0x3b, 0xac, 0x13, 0xf6, 0x9f, 0x33, 0xb3, 0xa0, 0x18, 0x2f, 0x26, 0x7a, 0xf3, 0x60, 0x3c,
	0x18, 0x2e, 0x7a, 0xf0, 0xe2, 0xf7, 0xf1, 0x2b, 0xf8, 0x41, 0xcc, 0xcc, 0x6c, 0xcb, 0x52, 0xc2,
	0xa1, 0x4d, 0xbc, 0xed, 0xbc, 0xcf, 0x3b, 0x6f, 0x7f, 0x33, 0xf3, 0x3c, 0x29, 0x34, 0x72, 0x41,
	0xb9, 0x70, 0x33, 0x9e, 0xca, 0x14, 0xdf, 0xed, 0xa7, 0xb1, 0x1b, 0x32, 0xf9, 0x3a, 0xef, 0xb9,
	0xbb, 0x3c, 0x0d, 0x39, 0x89, 0x63, 0x96, 0x84, 0xdb, 0xa4, 0xa7, 0x1a, 0x22, 0xd2, 0x0b, 0x48,
	0xbf, 0x9f, 0xe6, 0x89, 0x14, 0x2e, 0xc9, 0x98, 0x7d, 0x33, 0x4c, 0xd3, 0x30, 0xa2, 0x1e, 0xc9,
	0x98, 0x47, 0x92, 0x24, 0x95, 0x44, 0xb2, 0x34, 0x29, 0x86, 0xd9, 0x2b, 0x85, 0xaa, 0x57, 0xbd,
	0xfc, 0xc0, 0xa3, 0x71, 0x26, 0xdf, 0x15, 0x62, 0x67, 0x5c, 0x3c, 0x60, 0x34, 0x1a, 0x04, 0x31,
	0x11, 0x87, 0xa6, 0xc3, 0xf9, 0x84, 0xa0, 0xb2, 0x2f, 0x28, 0xc7, 0xd7, 0x61, 0x4e, 0x31, 0x06,
	0x6c, 0xd0, 0x46, 0x1d, 0xb4, 0x3e, 0xef, 0xd7, 0xd4, 0x72, 0x6b, 0x80, 0x31, 0x54, 0x12, 0x12,
	0xd3, 0xf6, 0x4c, 0x07, 0xad, 0x5b, 0xbe, 0xfe, 0xc6, 0x4b, 0x50, 0xa5, 0x31, 0x61, 0x51, 0x7b,
	0x56, 0x17, 0xcd, 0x02, 0xaf, 0x80, 0x75, 0x90, 0x47, 0x51, 0xa0, 0xdb, 0x2b, 0x5a, 0xa9, 0xab,
	0xc2, 0x8e, 0xda, 0xb2, 0x0a, 0x40, 0x8e, 0x88, 0x24, 0x3c, 0xc8, 0x79, 0xd4, 0xae, 0x6a, 0xd5,
	0x32, 0x95, 0x7d, 0x1e, 0x39, 0x3b, 0xb0, 0xb0, 0xcd, 0x84, 0x54, 0x28, 0xc2, 0xa7, 0x6f, 0x72,
	0x2a, 0xa4, 0xda, 0x92, 0x91, 0x90, 0x06, 0x32, 0x3d, 0xa4, 0x49, 0x41, 0x65, 0xa9, 0xca, 0x4b,
	0x55, 0x50, 0x3f, 0xa7, 0x65, 0xc1, 0x4e, 0x0c, 0x5d, 0xd5, 0xaf, 0xab, 0xc2, 0x1e, 0x3b, 0xa1,
	0xce, 0x67, 0x04, 0xad, 0xd2, 0x40, 0x91, 0xa5, 0x89, 0xa0, 0x78, 0x0b, 0xaa, 0xfa, 0x21, 0xda,
	0xa8, 0x33, 0xbb, 0xde, 0xe8, 0x6e, 0xb8, 0x13, 0xbd, 0x84, 0xab, 0x86, 0xf9, 0x66, 0x02, 0xbe,
	0x0d, 0x57, 0x13, 0xfa, 0x56, 0x06, 0x25, 0xc2, 0x19, 0x4d, 0x38, 0xaf, 0xca, 0xbb, 0x43, 0x4a,
	0xe7, 0x0e, 0x34, 0x37, 0xa9, 0xc6, 0x18, 0x1e, 0xeb, 0xb2, 0x9b, 0x76, 0xbe, 0x20, 0x68, 0x3d,
	0xe1, 0x94, 0x48, 0x5a, 0x6e, 0xdf, 0x84, 0x8a, 0xd2, 0x75, 0xef, 0x94, 0xc8, 0x7a, 0x00, 0xf6,
	0x60, 0x91, 0xd3, 0x90, 0x09, 0x49, 0xb9, 0x76, 0x50, 0x89, 0xda, 0xf2, 0xf1, 0x39, 0xc9, 0xa0,
	0x9f, 0x22, 0x68, 0xed, 0x67, 0x83, 0xff, 0xc5, 0x73, 0x1f, 0x1a, 0xb9, 0x9e, 0xae, 0xfd, 0xa8,
	0x39, 0x1a, 0x5d, 0xdb, 0x35, 0x96, 0x75, 0x87, 0x96, 0x75, 0x9f, 0x2b, 0xcb, 0xbe, 0x20, 0xe2,
	0xd0, 0x07, 0xd3, 0xae, 0xbe, 0x9d, 0x9f, 0x08, 0x96, 0x0d, 0xdb, 0x2e, 0x11, 0xe2, 0x38, 0xe5,
	0x83, 0x4b, 0xae, 0xd7, 0x1a, 0x19, 0xd9, 0x86, 0x7a, 0x56, 0xf4, 0x16, 0x87, 0x1e, 0xad, 0xf1,
	0x1a, 0x5c, 0x49, 0xe8, 0x71, 0x30, 0xd2, 0x8d, 0xaf, 0x1b, 0x09, 0x3d, 0x1e, 0x8e, 0xc7, 0x2e,
	0x2c, 0x96, 0x5b, 0x02, 0x4e, 0x33, 0x4a, 0x64, 0xe1, 0xf3, 0x56, 0xa9, 0xd3, 0xd7, 0x42, 0xf7,
	0x57, 0x0d, 0x1a, 0xea, 0xb4, 0x7b, 0x94, 0x1f, 0xb1, 0x3e, 0xc5, 0x3f, 0x10, 0x58, 0x23, 0x47,
	0xe2, 0x87, 0x13, 0xde, 0xdb, 0x78, 0x38, 0xec, 0x47, 0xd3, 0x0f, 0x30, 0x61, 0x70, 0x9a, 0x1f,
	0xff, 0xfc, 0xfd, 0x36, 0x53, 0xc7, 0x35, 0xcf, 0x38, 0xfa, 0x3b, 0x82, 0xb9, 0xc2, 0xaa, 0xf8,
	0xc1, 0x84, 0xd3, 0xcf, 0x5b, 0xdc, 0x9e, 0xc6, 0x15, 0x4e, 0x5b, 0xf3, 0x60, 0xbc, 0x60, 0x78,
	0xbc, 0xf7, 0xc5, 0x33, 0x7e, 0xc0, 0xa7, 0x08, 0xe0, 0x2c, 0x18, 0x78, 0xd2, 0xa3, 0x5f, 0xc8,
	0xd4, 0x74, 0x7c, 0x4b, 0x9a, 0xaf, 0xe9, 0x14, 0xf7, 0x75, 0xcf, 0xb8, 0xf8, 0x37, 0x02, 0x38,
	0x0b, 0xc9, 0xc4, 0x6c, 0x17, 0xf2, 0x35, 0x1d, 0xdb, 0x2d, 0xcd, 0xb6, 0xda, 0x5d, 0x2e, 0xdf,
	0x9d, 0x3b, 0xbc, 0xc0, 0x02, 0xf5, 0x2b, 0x82, 0xe6, 0xf9, 0xcc, 0xe0, 0xa7, 0x53, 0xe1, 0x8e,
	0x45, 0xce, 0xbe, 0x76, 0x21, 0xb4, 0xcf, 0xd4, 0x9f, 0x90, 0xb3, 0xa6, 0xa9, 0x56, 0xba, 0x37,
	0xc6, 0x5f, 0xd4, 0x1b, 0xa6, 0xe8, 0x71, 0xfd, 0x55, 0x8d, 0x64, 0x2c, 0xc8, 0x7a, 0xbd, 0x9a,
	0xde, 0xbc, 0xf1, 0x2f, 0x00, 0x00, 0xff, 0xff, 0x6d, 0x16, 0x35, 0x38, 0x2b, 0x07, 0x00, 0x00,
}
